#!/bin/sh
ulimit -c 0
total=0
pathsize=`/usr/bin/du -s --block-size=1 /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details --exclude=group | awk '{print $1}'`
total=$(($total+$pathsize))
group=0
group=`/usr/bin/du -s --block-size=1 /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details/group | awk '{print $1}'`
echo $group > /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details/group/duse_group.tmp && \
mv /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details/group/duse_group.tmp /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details/group/duse_group
pathsize=`/usr/bin/du -s --block-size=1 /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/RISCV1.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details/duse_manager_res.tmp && \
mv /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details/duse_manager_res.tmp /project/tsmc28mmwave/users/foqara/ws/riscv/signoff_drc_run/run_details/duse_manager_res
